version: '3.4'

services:
  codebelt.webapp.razor:
    image: ${DOCKER_REGISTRY-}codebeltwebapprazor
    build:
      context: src/Codebelt.WebApp.Razor/.
      dockerfile: Dockerfile
  codebelt.webapp.razor.app:
    image: codebeltnet/web-cdn-origin:1.2.0
    ports:
      - "8010:80"
    volumes:
      - ./src/Codebelt.WebApp.Razor/approot:/cdnroot
  codebelt.webapp.razor.cdn:
    image: codebeltnet/web-cdn-origin:1.2.0
    ports:
      - "8020:80"
    volumes:
      - ./src/Codebelt.WebApp.Razor/cdnroot:/cdnroot