stages:
  - stage: BuildDevelopment
    displayName: 'Build for preview'
    condition: and(succeeded(), endsWith(variables['build.sourceBranch'], 'main'))
    variables:
      - group: BuildSecrets
      - name: BuildSource
        value: 'src'
      - name: BuildConfiguration
        value: 'Debug'
    jobs:
    - template: ../jobs/build-development.yml
      parameters:
        selfHosted: ${{ parameters.selfHosted }}
        linuxVmImage: ${{ parameters.linuxVmImage }}
        windowsVmImage: ${{ parameters.windowsVmImage }}

  - stage: BuildMain
    displayName: 'Build for production'
    condition: and(succeeded(), endsWith(variables['build.sourceBranch'], 'main'))
    variables:
      - group: BuildSecrets
      - name: BuildSource
        value: 'src'
      - name: BuildConfiguration
        value: 'Release'
    jobs:
    - template: ../jobs/build-production.yml
      parameters:
        selfHosted: ${{ parameters.selfHosted }}
        linuxVmImage: ${{ parameters.linuxVmImage }}
        windowsVmImage: ${{ parameters.windowsVmImage }}

  - stage: DeployDevelopment
    displayName: 'Deployment for development branch'
    condition: and(succeeded(), endsWith(variables['build.sourceBranch'], 'main'))
    dependsOn: 
      - BuildDevelopment
    variables:
    - group: BuildSecrets
    jobs:
    - template: ../jobs/deployment-development.yml
      parameters:
        selfHosted: ${{ parameters.selfHosted }}
        linuxVmImage: ${{ parameters.linuxVmImage }}
        windowsVmImage: ${{ parameters.windowsVmImage }}

  - stage: DeployMain
    displayName: 'Deployment for main branch'
    condition: and(succeeded(), endsWith(variables['build.sourceBranch'], 'main'))
    dependsOn: 
      - BuildMain
    variables:
    - group: BuildSecrets
    jobs:
    - template: ../jobs/deployment-production.yml
      parameters:
        selfHosted: ${{ parameters.selfHosted }}
        linuxVmImage: ${{ parameters.linuxVmImage }}
        windowsVmImage: ${{ parameters.windowsVmImage }}