jobs:
  - job: BuildDotNet6_0
    displayName: 'Build final (net6.0, build)'
    timeoutInMinutes: 15
    pool:
      ${{ if eq(parameters.selfHosted, 'true') }}:
        name: ${{ parameters.windowsVmImage }}
      ${{ if eq(parameters.selfHosted, 'false') }}:
        vmImage: ${{ parameters.windowsVmImage }}
    variables:
      - name: DotnetBuildName
        value: 'net6.0'
    steps:
    - template: ../steps/dotnet.yml
    - template: ../steps/restore.yml
    - template: ../steps/build-net6_0.yml
    - template: ../steps/publish-artifact.yml
      parameters:
        artifactName: "productionSrc"

  - job: PublishBuildArtifacts
    condition: succeeded()
    dependsOn:
    - BuildDotNet6_0
    displayName: 'Store NuGet Packages for Production'
    timeoutInMinutes: 30
    pool:
      ${{ if eq(parameters.selfHosted, 'true') }}:
        name: ${{ parameters.windowsVmImage }}
      ${{ if eq(parameters.selfHosted, 'false') }}:
        vmImage: ${{ parameters.windowsVmImage }}
    variables:
      - name: ArtifactPackageName
        value: 'Production'
    steps:
    - template: ../steps/dotnet.yml
    - template: ../steps/publish-nuget.yml
      parameters:
        artifactName: "productionSrc"
        artifactPackages:
          - "net6.0"