jobs:
  - job: BuildDotNet6_0
    displayName: 'Build preview (net6, build)'
    timeoutInMinutes: 15
    strategy:
      matrix:
        Linux_Build_and_Test:
          imageName: ${{ parameters.linuxVmImage }}
        Windows_Build_Test_and_Package:
          imageName: ${{ parameters.windowsVmImage }}
    pool:
      ${{ if eq(parameters.selfHosted, 'true') }}:
        name: $(imageName)
      ${{ if eq(parameters.selfHosted, 'false') }}:
        vmImage: $(imageName)
    variables:
      - name: DotnetBuildName
        value: 'net6.0'
    steps:
    - template: ../steps/dotnet.yml
    - template: ../steps/restore.yml
    - template: ../steps/build-net6_0.yml
    - template: ../steps/publish-artifact.yml
      parameters:
        artifactName: "previewSrc"

  - job: PublishBuildArtifacts
    condition: succeeded()
    dependsOn:
    - BuildDotNet6_0
    displayName: 'Store NuGet Packages for Preview'
    timeoutInMinutes: 30
    pool:
      ${{ if eq(parameters.selfHosted, 'true') }}:
        name: ${{ parameters.windowsVmImage }}
      ${{ if eq(parameters.selfHosted, 'false') }}:
        vmImage: ${{ parameters.windowsVmImage }}
    variables:
      - name: ArtifactPackageName
        value: 'Preview'
    steps:
    - template: ../steps/dotnet.yml
    - template: ../steps/publish-nuget.yml
      parameters:
        artifactName: "previewSrc"
        artifactPackages:
          - "net6.0"